server:
  port: 8082

spring:
  application:
    name: team-service

external:
  service:
    url: http://localhost:8080
    timeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://eurekaadmin:eurekapass@localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30